import Link from "next/link";
import Navbar from "@/components/Navbar";

const sections = [
  {
    title: "Acceptance of Terms",
    content:
      "By accessing or using GithuV, you agree to be bound by these Terms and Conditions. If you do not agree, do not use the platform. We reserve the right to update these terms at any time; continued use constitutes acceptance of changes.",
  },
  {
    title: "Account Registration",
    content:
      "You must authenticate via GitHub OAuth to use GithuV. You are responsible for maintaining the confidentiality of your account and for all activities under your account. You must provide accurate information and keep it updated.",
  },
  {
    title: "GitHub Data & Permissions",
    content:
      "GithuV requests read-only access to your GitHub profile, repositories, and activity data to power its features. We never modify repositories, code, or settings without your explicit action. You can revoke access at any time via your GitHub settings.",
  },
  {
    title: "AI-Generated Content",
    content:
      "Content generated by AI (resumes, READMEs, LinkedIn posts, coaching suggestions) is provided as a starting point. You are solely responsible for reviewing, editing, and approving all AI-generated output before publishing or using it professionally.",
  },
  {
    title: "User Content",
    content:
      "You retain all rights to the content you create on GithuV. By using the platform, you grant us a limited license to store, process, and display your content solely for providing the service. We do not claim ownership of your data.",
  },
  {
    title: "Acceptable Use",
    content:
      "You agree not to misuse GithuV for spam, abuse, impersonation, illegal activity, or any action that disrupts the platform or violates others' rights. We reserve the right to suspend accounts that violate these terms.",
  },
  {
    title: "Service Availability",
    content:
      "GithuV is provided 'as is' without warranties of uptime or error-free operation. We strive for high availability but do not guarantee uninterrupted service. We are not liable for damages arising from service interruptions or data loss.",
  },
  {
    title: "Limitation of Liability",
    content:
      "GithuV and its contributors shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform. Your sole remedy is to discontinue use.",
  },
  {
    title: "Privacy",
    content:
      "Your privacy matters. We only collect data necessary to provide the service (GitHub profile data, usage analytics). We do not sell your data. See our platform for more details on how your data is handled.",
  },
  {
    title: "Changes to Terms",
    content:
      "We may update these terms from time to time. Material changes will be communicated via the platform or email. Your continued use after changes take effect constitutes acceptance of the updated terms.",
  },
  {
    title: "Contact",
    content:
      "For questions about these terms, reach out through the GithuV platform or open an issue on our GitHub repository.",
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <Navbar showAuth={false} />

      <section className="relative px-5 pt-32 pb-16 overflow-hidden">
        <div className="absolute inset-x-0 top-0 h-96 bg-[radial-gradient(circle_at_50%_0%,rgba(239,68,68,0.10),transparent_60%)]" />
        <div className="absolute inset-0 githuv-hero-grid opacity-20" />

        <div className="relative z-10 mx-auto max-w-3xl text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-red-500/20 bg-red-500/10 px-4 py-2 text-sm font-medium text-red-100">
            <span className="size-2 rounded-full bg-red-400 githuv-pulse-dot" />
            Terms & Conditions
          </div>
          <h1 className="mt-6 text-4xl font-black tracking-tight sm:text-5xl">
            Terms of Service
          </h1>
          <p className="mx-auto mt-4 max-w-xl text-neutral-400">
            Last updated: June 2026
          </p>
        </div>
      </section>

      <section className="px-5 py-10 pb-24">
        <div className="mx-auto max-w-3xl space-y-8">
          {sections.map((s, i) => (
            <div
              key={s.title}
              className="rounded-xl border border-white/10 bg-neutral-900/60 p-6 transition duration-300 hover:border-white/20 hover:bg-neutral-900"
            >
              <div className="flex items-start gap-4">
                <span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg border border-red-500/20 bg-red-500/10 text-sm font-bold text-red-300">
                  {i + 1}
                </span>
                <div>
                  <h2 className="text-lg font-bold">{s.title}</h2>
                  <p className="mt-2 leading-7 text-neutral-400">{s.content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <footer className="border-t border-white/10 px-5 py-8">
        <div className="mx-auto flex max-w-7xl flex-col items-center gap-3 text-sm text-neutral-500 sm:flex-row sm:justify-between">
          <Link href="/" className="text-xl font-black italic tracking-tight text-white">
            Githu<span className="text-red-500">V</span>
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/about" className="transition hover:text-white">About</Link>
            <Link href="/terms" className="transition hover:text-white">Terms</Link>
            <Link href="/developer" className="transition hover:text-white">Developer</Link>
          </div>
          <span>GithuV — AI-Powered Career Growth Platform for Developers</span>
        </div>
      </footer>
    </main>
  );
}
